/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue.graph;

import java.awt.Color;
import javax.swing.JOptionPane;
import modele.Employe;
import modele.ProjModele;

/**
 *
 * @author tiffany.deschinckel
 */
public class EncodeEmploye extends javax.swing.JPanel {
    private ProjModele pm;
    
    /**
     * Creates new form EncodeEmploye
     */
    public EncodeEmploye() {
        initComponents();
    }
    
    public void setModele(ProjModele pm){
        this.pm=pm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbNom = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        lbPrenom = new javax.swing.JLabel();
        tfPrenom = new javax.swing.JTextField();
        lbGsm = new javax.swing.JLabel();
        tfGsm = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btEncoder = new javax.swing.JButton();
        btEffacer = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        lbNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNom.setText("Nom :");

        tfNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomActionPerformed(evt);
            }
        });

        lbPrenom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPrenom.setText("Prénom :");
        lbPrenom.setMaximumSize(new java.awt.Dimension(65, 29));
        lbPrenom.setMinimumSize(new java.awt.Dimension(65, 29));
        lbPrenom.setPreferredSize(new java.awt.Dimension(65, 29));

        tfPrenom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrenomActionPerformed(evt);
            }
        });

        lbGsm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbGsm.setText("GSM :");

        tfGsm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbEmail.setText("Email :");

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        btEncoder.setLabel("Encoder");
        btEncoder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncoderActionPerformed(evt);
            }
        });

        btEffacer.setText("Effacer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(lbGsm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPrenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNom)
                            .addComponent(tfPrenom)
                            .addComponent(tfGsm)
                            .addComponent(tfEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 173, Short.MAX_VALUE)
                        .addComponent(btEncoder, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNom, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(lbNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbGsm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfGsm, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btEffacer, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(btEncoder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomActionPerformed

    private void tfPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrenomActionPerformed

    private void btEncoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncoderActionPerformed
        tfNom.setBackground(Color.white);
        tfPrenom.setBackground(Color.white);
        tfGsm.setBackground(Color.white);
        tfEmail.setBackground(Color.white);

        boolean erreur = false;

        String nom = tfNom.getText();
        if (nom.trim().equals("")) {
            erreur = true;
            tfNom.setBackground(Color.red);
        }

        String prenom = tfPrenom.getText();
        if (prenom.trim().equals("")) {
            erreur = true;
            tfPrenom.setBackground(Color.red);
        }

        String gsm = tfGsm.getText();
        if (gsm.trim().equals("")) {
            erreur = true;
            tfGsm.setBackground(Color.red);
        }

        String email = tfEmail.getText();
        if (email.trim().equals("")) {
            erreur = true;
            tfEmail.setBackground(Color.red);
        }
        
        if(!erreur){
            Employe e = new Employe(nom,prenom,gsm,email);
            String msg = pm.ajouterObjet(e);
            JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btEncoderActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEffacer;
    private javax.swing.JButton btEncoder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGsm;
    private javax.swing.JLabel lbNom;
    private javax.swing.JLabel lbPrenom;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGsm;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    // End of variables declaration//GEN-END:variables
}
